services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ami_ci_django
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - ./.envs/.ci/.django
      - ./.envs/.ci/.postgres
    command: /start

  postgres:
    image: postgres:13
    env_file:
      - ./.envs/.ci/.postgres

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: ami_ci_celeryworker
    command: /start-celeryworker

  minio:
    image: minio/minio:latest
    command: minio server --console-address ":9001" /data
    env_file:
      - ./.envs/.ci/.django
