services:
  django: &django
    build:
      context: .
      # This is the most important setting to test the production configuration of Django.
      dockerfile: ./compose/production/django/Dockerfile
    image: insectai/ami_backend
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      - ./config:/app/config
    ports:
      - "5001:5000"
    extra_hosts:
      - "db:${DATABASE_IP}"
      - "redis:${REDIS_IP}"
    command: /start
    scale: 0  # Can't scale until the load balancer is within the compose config
    restart: always

  celeryworker:
    <<: *django
    scale: 1
    ports: []
    command: /start-celeryworker
    restart: always
