version: "3"

volumes:
  ami_local_postgres_data: {}
  ami_local_postgres_data_backups:
    driver: local
    driver_opts:
      type: none
      device: ./backups/local/postgres
      o: bind
  minio_data:
    driver: local

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ami_local_django
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - ami_local_postgres_data:/var/lib/postgresql/data
      - ami_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: ami_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ami:/app/ami:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: ami_local_redis

  celeryworker:
    <<: *django
    image: ami_local_celeryworker
    scale: 1
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ami_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: ami_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  minio:
    # image: minio/minio
    image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
    command: minio server /data --console-address "0.0.0.0:9001"
    volumes:
      - "minio_data:/data"
    # - ./config/minio:/etc/config.env
    env_file:
      - ./.envs/.local/.django
    expose:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
