# This is a transitional production configuration.
# Redis and celery will be external services in the final production configuration.
# Traffic or NGINX may or may not be used in the final production configuration
# but the Django container will not expose its port to the host (there will be more than one container).
version: "3"

volumes:
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: ami_production_django
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "5000:5000"

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: ami_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ami_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: ami_production_flower
    command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
