# Identical to production.yml, but with the following differences:
# Uses the django production settings file, but staging .env file.
# Uses "local" database
#
# 1. The database is a service in the Docker Compose configuration rather than external as in production.
# 2. Redis is a service in the Docker Compose configuration rather than external as in production.
# 3. Port 8000 is exposed for the Django application.
version: "3"

volumes:
  ami_local_postgres_data: {}
  ami_local_postgres_data_backups:
    driver: local
    driver_opts:
      type: none
      device: ./backups/postgres
      o: bind

services:
  django: &django
    build:
      context: .
      # This is the most important setting to test the production configuration of Django.
      dockerfile: ./compose/production/django/Dockerfile

    image: ami_staging_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.local/.postgres
    volumes:
      - ./config:/app/config
    ports:
      - "5000:5000"
    command: /start

  postgres:
    build:
      context: .
      # There is not a local/staging version of the Postgres Dockerfile.
      dockerfile: ./compose/production/postgres/Dockerfile
    # Share the local Postgres image with the staging configuration.
    # Production uses an external Postgres service.
    image: ami_local_postgres
    volumes:
      - ami_local_postgres_data:/var/lib/postgresql/data
      - ami_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    restart: always

  redis:
    image: redis:6
    container_name: ami_staging_redis

  celeryworker:
    <<: *django
    image: ami_staging_celeryworker
    scale: 1
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ami_staging_celerybeat
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: ami_staging_flower
    ports:
      - "5550:5555"
    command: /start-flower
