[[redirects]]
# Serve the api docs from /api/
from = "/api/"
to = "https://api.dev.insectai.org/docs/"
status = 200
force = true
headers = { X-From = "Netlify" }

[[redirects]]
# Serve the external api endpints from /api/*
from = "/api/*"
to = "https://api.dev.insectai.org/api/:splat"
status = 200
force = true
headers = { X-From = "Netlify" }

[[redirects]]
# Serve the external images from from /static/images/*
from = "/static/captures/*"
to = "https://api.dev.insectai.org/static/captures/:splat"
status = 200
force = true
headers = { X-From = "Netlify" }

[[redirects]]
# Serve the external images from from /static/images/*
from = "/static/crops/*"
to = "https://api.dev.insectai.org/static/crops/:splat"
status = 200
force = true
headers = { X-From = "Netlify" }

[[redirects]]
# Redirect all other paths to the root for React to handle
from = "/*"
to = "/"
status = 200
force = false
